### ISSUE TITLE
error while upgrade package and creating new user

### ISSUE THREAD

**Issue by JSilaban** [SDRausty/termux-archlinux#54]
i have problem on my android 10, while upgrading package using `pacman -Syu` and the result :

> error: could not open file: /etc/mtab: No such file or directory
> error: could not determine filesystem mount points
> error: failed to commit transaction (unexpected error)
> Errors occurred, no packages were upgraded.

and while creating a new user using `startarch c adduser user` and the result :

> /bin/bash: adduser: command not found

i hope this not duplicate. thanks

**Comment by starblade09** [comment]
I am having the same issue as well
```
pacman -Syu                    
:: Synchronizing package databases...                 error: failed to update core (no servers configured for repository)                                         error: failed to update extra (no servers configured for repository)                                        error: failed to update community (no servers configured for repository)                                    error: failed to update alarm (no servers configured for repository)                                        error: failed to update aur (no servers configured for repository)                                          error: failed to synchronize all databases
```

Started this morning out of nowhere.  At first it was an `error: 403`, or `milisecond` timeouts then thought my personal distro was depricated, only to find out it wasnt,because I did `purge` and reinstalled.  And now, its even worse than before.

**Comment by starblade09** [comment]
Sorry to double comment here, since this isn't even my own contribution thread"! but here we go my friend

Seems one way or another, our defaulted mirrorlist, or even servers on `/pacman.d` dir, are inappropriately configured. 

To simplify what I am talking about, follow these steps for the solution.

Going into your `arch` root directory to find the conf files.
`cd (your)/(path)/(to)/(your own root)/arch

cd arch/etc/pacman.d/`

replace the ( - ) filepaths with your own directory setup, as each of us have a different directory

`vim mirrorlist`

Now, right here , you have two options: using the defaulted mirrors on the `mirrorlist` , or generating new ones on the offical arch repo website  
https://www.archlinux.org/mirrorlist/
 
I just used the default ones and I was good to go. It will look somewhat like this:


```
##
## Arch Linux repository mirrorlist
## Generated on 2020-03-29
##

## Worldwide
#Server =
http://mirrors.evowise.com/archlinux/$repo/os/$arch
#Server = http://mirror.rackspace.com/archlinux/$repo/os/$arch
#Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
```
No matter what way you want to go about taking care of these mirrors, you have to make sure you uncomment (removing # symbol) from where it says `#Server=`

So just to give you another example, look at the differences between this new mirrorlist

```
##
## Arch Linux repository mirrorlist
## Generated on 2020-03-29
##

## Worldwide
#Server = http://mirrors.evowise.com/archlinux/$repo/os/$arch
#Server = http://mirror.rackspace.com/archlinux/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
```
When you compare these two mirrorlists, you'll see that the third line has been modified in WorldWide server in 3rd mirrorlink.

Afterwards, save your changes (^X) , exit out of Arch, start it back up , then immediately go ahead and `pacman -Syu`

I hope this helps!

**Comment by SDRausty** [comment]
> startarch c adduser user 

`startarch c addauser user`

`which addauser | xargs cat`

**Comment by Focshole** [comment]
Look, you have done a typo. It's addAuser, `addauser`, not `adduser`

**Comment by woshiluo** [comment]
> i have problem on my android 10, while upgrading package using `pacman -Syu` and the result :
> 
> > error: could not open file: /etc/mtab: No such file or directory
> > error: could not determine filesystem mount points
> > error: failed to commit transaction (unexpected error)
> > Errors occurred, no packages were upgraded.
> 
> and while creating a new user using `startarch c adduser user` and the result :
> 
> > /bin/bash: adduser: command not found
> 
> i hope this not duplicate. thanks

Same problem with you, have you solved this problem?

```
[root09:44home]$ pacman -S vim
resolving dependencies...
looking for conflicting packages...

Packages (3) gpm-1.20.7.r27.g1fd1941-2  vim-runtime-8.2.0510-2  vim-8.2.0510-2

Total Download Size:    7.32 MiB
Total Installed Size:  33.63 MiB

:: Proceed with installation? [Y/n] 
error: could not open file: /etc/mtab: No such file or directory
error: could not determine filesystem mount points
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```
I'm using android 10 on Redmi Note 5.d
