### ISSUE TITLE
How to Uninstall!?!

### ISSUE THREAD

**Issue by turbomaster95** [SDRausty/termux-archlinux#90]
I was just cleaning up my phone and I deleted the arch folder
And the Path "/data/data/com.termux/files/home/arch/etc/ca-certificates/extracted/cadir"
Said it couldn't delete it 
Pls help
Screenshot :
![Screenshot_2022-03-10-18-16-18-175](https://user-images.githubusercontent.com/86113389/157664622-3292e6f2-b3e2-499e-a385-2d7085d4ebd0.jpeg)

**Comment by SDRausty** [comment]
`bash setupTermuxArch purge`

```
[purge [customdir]]  Purge Arch Linux option with function _RMARCHRM_.

[p[urge] [customdir]] Quick purge Arch Linux option with function _RMARCHRM_.
```

`bash setupTermuxArch help` has more information.  Thank you for using `setupTermuxArch`, and why are you uninstalling?

**Comment by SDRausty** [comment]
>why are you uninstalling Linux from your phone?

The reason I am asking is to assist in developing features such as [`USECACHEDIR=1		##  change to 0 to use cache directory;  When changed to 0 this installation script uses a cache directory defined in `necessaryfunctions.bash` that can be used to cache all of the installation files in order to save wireless bandwidth upon subsequent reinstallation.  Variable `KEEP=1`  should be changed to 0 also in order to keep the downloaded image file and md5 files. The downloaded image and md5 files should be moved to CACHEDIR along with files in INSTALLDIR/var/cache/pacman/pkg in order to avoid subsequent redownloading of these files for reinstalling the entire system`](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L17) that will hopefully give this script more fuctionality within the computer environment that we are blessed to have for the end user.
